[package]
name = "rust_tls_atexit"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_tls_atexit"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py38"] }